parameters:
    homepage_settings:
        left_menu: %left_menu%
        right_menu: %right_menu%
#    sf_tblog_blog.example.class: sfTblog\BlogBundle\Example

services:
#    sf_tblog_blog.example:
#        class: %sf_tblog_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
