### OTHER PARAMETERS ###
parameters: 
  # The name of default user avtar image.
  default_avatar_image_name:    default.png
  
  # TitIt mailer parameters
  site_mailer_parameters:
    address:      info@TitIt.ws
    sender_name : TitIt.ws
    
# app/config/config.yml
#knp_snappy:
#    pdf:
#        enabled:    true
#        binary:     /usr/bin/wkhtmltopdf
#        options:    []
#    image:
#        enabled:    true
#        binary:     /usr/local/bin/wkhtmltoimage
#        options:    []